version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - haribote
  - isoden
  - NaokiMatsuda
  - oti
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
